name: Deploy docs

on:
  push:
    paths:
      - 'docs/**'
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docs

    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Restart Node Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script_stop: true # Stop executing on first failure.
          script: |
            cd /var/www/fimgaid
            git fetch origin main
            git reset --hard FETCH_HEAD
