# Downloads mdbook (https://github.com/rust-lang/mdBook),
# builds the documentation and uploads to Cloudflare Pages

name: Deploy docs

on:
  push:
    paths:
      - 'docs/**'
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy docs

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download mdbook binary
        run: curl -fsSL https://github.com/rust-lang/mdBook/releases/download/v0.4.22/mdbook-v0.4.22-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=/bin

      - name: Build documentation
        run: /bin/mdbook build docs

      - name: Publish book
        run: CLOUDFLARE_ACCOUNT_ID=${{ secrets.CLOUDFLARE_ACCOUNT_ID }} CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} npx wrangler pages publish --project-name=figmaid docs/book
