name: Release

defaults:
  run:
    shell: bash

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  ci:
    name: CI
    uses: ./.github/workflows/ci.yml

  release:
    needs: ci
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build project
        run: cargo build --release --locked

      - name: Upload binary
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/figmaid
          asset_name: figmaid-ubuntu-amd64
          tag: ${{ github.ref }}
          overwrite: true

  docker_image:
    needs: ci
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nykanen/figmaid:latest,nykanen/figmaid:${{ github.ref }}
